spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testeTGID
    username: postgres
    password: admin123
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${JAVAMAILSENDER_EMAIL}
    password: ${JAVAMAILSENDER_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true