spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/testeTGID
    username: ${POSTGRESQL_USER}
    password: ${POSTGRESQL_PASSWORD}
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_SENDER}
    password: ${PASSWORD_EMAIL_SENDER}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true